services:
  php:
    build: infra/docker/php-8.3
    ports:
      - 8000:8000
    volumes:
      - .:/app
    entrypoint: tail -f /dev/null
    environment:
      - DATABASE_URL=mysql://root:mysql@mysql:3306/TheMovieDB?charset=utf8mb4&serverVersion=8.0.31

  mysql:
    image: 'mysql:8.0.35'
    restart: always
    volumes:
      - ./infra/volumes/mysql_data:/var/lib/mysql
    command: mysqld --sql_mode="NO_ENGINE_SUBSTITUTION"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=TheMovieDB
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    links:
      - mysql
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=mysql
